services:
  database: 
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: routine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: guieduda1731
    ports:
      - "5442:5442"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"


  application:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
        DB_NAME: routine
        DB_USER: postgres
        DB_PASSWORD: guieduda1731
        DB_HOST: database
        DB_PORT: 5432
volumes:
  postgres_data: 