# Generated by Django 5.1.3 on 2024-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='caption',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
